### ISSUE TITLE
[1.0.0.2] Request: support simple text files as lists for batch download

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/NijieDownloader#10]
This is more useful for member id lists, much like "pixiv downloader" tool supports parsing the list.txt file.

Format is 1 line = 1 id:
11122
22333
44455
...

**Comment by chronometric** [comment]
Wanted to say this is really the only feature missing from this excellent program/gui. This is one of the best capabilities of PixivUtil, as it makes deciding which groups of artists to download a trivial copy/paste task, instead of plodding artist by artist (and again to renew your "watch list" artists). Would be most welcome in this program as well!

**Comment by chronometric** [comment]
If this is difficult to implement without lots of new coding...might it be possible to allow the entry of multiple user IDs in the "Add" window? That way they could all be added to the queue with the same page/filename syntax options.

**Comment by Nandaka** [comment]
implemented the list.txt, it will only load as member id.
